### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by EvilZane** [SpaceGameDev568/Factory_Prop_Mod#20] opened 2024-11-09 21:01 UTC
If you place an Oilpump the game crasches.

**Comment by SpaceGameDev568** [comment] 2024-11-09 21:12
Thanks for taking the time to create a report! I have determined the cause of the issue and will have it fixed in the next update.

**Comment by SpaceGameDev568** [comment] 2024-11-09 22:36
Fixed in Factory Props v2.0.4, which is available to download now.

**Closed as completed by SpaceGameDev568** 2024-11-09 22:36 UTC
